In [14]:
import torch


In [15]:
code_book = torch.tensor([[0,1],[2,3],[4,5],[6,7],[8,9]])
proj_data = torch.tensor([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print(code_book.shape) # [vocab_size, code_book_dim]
print(proj_data.shape) # [batch_size, seq_len, embedding_dim(same as embedding dim)]

torch.Size([5, 2])
torch.Size([3, 3, 2])


In [16]:
proj_data = torch.unsqueeze(proj_data,2)
tmp = torch.sub(proj_data,code_book)
norm2 = torch.squeeze(torch.sum(tmp ** 2, dim=-1)) # get the distance between each vector and each codebook
print(norm2,norm2.shape)
labels = torch.argmin(norm2, dim=-1) # get the index of the nearest codebook
print(labels, labels.shape)

tensor([[[  2,   2,  18,  50,  98],
         [ 18,   2,   2,  18,  50],
         [ 50,  18,   2,   2,  18]],

        [[ 98,  50,  18,   2,   2],
         [162,  98,  50,  18,   2],
         [242, 162,  98,  50,  18]],

        [[338, 242, 162,  98,  50],
         [450, 338, 242, 162,  98],
         [578, 450, 338, 242, 162]]]) torch.Size([3, 3, 5])
tensor([[0, 1, 2],
        [3, 4, 4],
        [4, 4, 4]]) torch.Size([3, 3])


In [17]:
criterion = torch.nn.CrossEntropyLoss()
labels = torch.unsqueeze(labels.flatten()[0:5],0)
labels

tensor([[0, 1, 2, 3, 4]])

In [32]:
output = torch.tensor([[100,-10,0,0,0],[0,0,0,0,0],[1,2,10,1,1],[1,1,5,100,1],[1,1,1,1,100]])
output = torch.unsqueeze(output,0)

In [33]:
criterion(output.float(), labels)

tensor(0.5267)